config/routes.rb
Rails.application.routes.draw do
  get 'profiles/show'

  get 'dashboard/listed'
  get 'dashboard/requested'
  get 'dashboard', to: 'dashboard#index', as: 'dashboard'

  devise_for :users
  resources :gifts
  root 'landing#index'

  
  get 'profiles/:id', to: 'profiles#show', as: 'profile' 
  
  post 'gifts/:id/request_gift' => 'gifts#request_gift', as: :request_gift

  get 'gifts/:id/jaz', to: 'gifts#jaz'

end

app/models/gift.rb
class Gift < ActiveRecord::Base
  # Similar to whitespace get the whole team on one type of tab
  # I would suggest 2 spaces for a tab. Seems like a small thing
  # but different editors show tabs differently and it messes
  # with indentation making the code harder to read.
	validates :title, presence: true
  validates :description, presence: true

	belongs_to :user
 	has_many :requests

end

app/models/request.rb
class Request < ActiveRecord::Base
  validates :message, presence: true
  
  belongs_to :user
  belongs_to :gift

# // only allow one request (per gift) for each user
  validates_uniqueness_of :user, scope: :gift 
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  	devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

    has_many :gifts
    has_many :requests

  	def full_name
  		"#{first_name} #{last_name}"
  	end 

    def has_requested?(gift)
      requests.where(gift_id: gift.id).exists?
    end 

    def request_for(gift)
      requests.where(gift_id: gift.id).first
    end 
         
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?

    protected

   def configure_permitted_parameters
     devise_parameter_sanitizer.for(:sign_up) << [:first_name, :last_name, :profile_name, :location] 
   end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  # Minor niggle but try to remove trailing whitespace
  
  def index 
  end 

  def listed
  end

  def requested
  end 

end

app/controllers/gifts_controller.rb
class GiftsController < ApplicationController
  before_action :set_gift, only: [:show, :edit, :update, :destroy]

  # GET /gifts
  # GET /gifts.json
  def index
    return redirect_to root_url unless current_user
    @gifts = Gift.order('created_at DESC').all
    @gift = Gift.new
    # @user = User.new

    # respond_to // still see html page. User goes to /gifts, renders gifts view, then JS will ask server for gifts json 
    respond_to do |format|
      format.html 
      format.json { render json: @gifts}
    end    

  end

  # GET /gifts/1
  # GET /gifts/1.json
  def show
    @request = Request.new 
    @gift = Gift.find(params[:id])
    respond_to do |format|
      format.html 
      format.json { render json: @gift }
    end 
  end

  # GET /gifts/new
  def new
    return redirect_to new_user_session_path unless current_user
    @gift = Gift.new
  end

  # GET /gifts/1/edit
  def edit
    return redirect_to new_user_session_path unless current_user == @gift.user 
  end

  # POST /gifts
  # POST /gifts.json
  def create
    return redirect_to new_user_session_path unless current_user
    @gift = Gift.new(gift_params)
    @gift.user = current_user 

    respond_to do |format|
      if @gift.save
        format.html { redirect_to dashboard_listed_path, notice: 'Gift was successfully created.' }
        format.json { render :show, status: :created, location: @gift }
      else
        format.html { render :new }
        format.json { render json: @gift.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gifts/1
  # PATCH/PUT /gifts/1.json
  def update
    return redirect_to new_user_session_path unless current_user == @gift.user 
    respond_to do |format|
      if @gift.update(gift_params)
        format.html { redirect_to @gift, notice: 'Gift was successfully updated.' }
        format.json { render :show, status: :ok, location: @gift }
      else
        format.html { render :edit }
        format.json { render json: @gift.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gifts/1
  # DELETE /gifts/1.json
  def destroy
    @gift.destroy
    respond_to do |format|
      format.html { redirect_to gifts_url, notice: 'Gift was successfully removed.' }
      format.json { head :no_content }
    end
  end

  # api endpoint for new request
  # post "/gifts/:id/request" do
  def request_gift
    # find the gift by its ID
    @gift = Gift.find(params[:id])
    # create a new request object that's set to current user and current gift
    @request = Request.new
    @request.user = current_user
    @request.gift = @gift

    # binding.pry 
    @request.message = params[:request][:message]
    # save this request & return json object containing the new request
    if @request.save
      respond_to do |format|
        format.html { redirect_to gift_path(@gift), notice: "Your request has been received."}
        format.json { render request: @request}
      end
    else
      status 400
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gift
      @gift = Gift.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gift_params
      params.require(:gift).permit(:title, :description, :type, :comments, :image)
    end
end

app/controllers/landing_controller.rb
class LandingController < ApplicationController

  def index 
    if current_user 
      redirect_to gifts_path
    else 
      render layout: "landing"
    end   
  end 
  
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def show
    # Don't commit commented out code
    # @user = User.find_by_profile_name(params[:id])
    @user = User.find(params[:id])
    if @user 
      # By default the association will give you all gifts for this user so you
      # don't need to call all after.
      @gifts = @user.gifts.all 
      render action: :show 
    else 
      render file: 'public/404', status: 404, formats: [:html]
    end 

  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def resource_name
    :user
  end
  
  def resource
    @resource ||= User.new
  end
  
  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/dashboard_helper.rb
# Don't commit empty files. Any empty helpers should just be deleted.
module DashboardHelper
end

app/helpers/gifts_helper.rb
module GiftsHelper
end

app/helpers/landing_helper.rb
module LandingHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/dashboard/index.html.erb
<h1>Dashboard</h1>

<div class="container-inner">

  <!-- tabs -->
  <ul class="nav nav-tabs" role="tablist">
    <li class="active"><a href="#my-gifts" role="tab" data-toggle="tab">Items I'm Giving Away</a></li>
    <li><a href="#my-requests" role="tab" data-toggle="tab">Items I've Requested</a></li>
    <li><a href="#my-requests" role="tab" data-toggle="tab">Profile</a></li>
  </ul>

  <!-- Tab panes -->
  <div class="tab-content">
    <div class="tab-pane active" id="my-gifts">
      <br>
      <% current_user.gifts.each do | gift| %>
        <div class="row">
          <div class="col-xs-2 ">
            <a href="/gifts/<%= gift.id %>">
              <%= gift.title %>
            </a>
          </div>
          <div class="col-xs-10 ">
            <em><%= gift.description %></em>
          </div>      
        </div>  
        <br>    
      <% end %>   

    </div>      
  

    <div class="tab-pane" id="my-requests">  
      <br>
            <% current_user.requests.each do | request | %>
              <div>
                <a href="/gifts/<%= request.gift.id %>">
                  <%= request.gift.title %>
                </a>
              </div>
            <% end %>      

    </div>
</div>

app/views/dashboard/listed.html.erb
<h1>Dashboard#listed</h1>
<p>Find me in app/views/dashboard/index.html.erb</p>

<ul class="nav nav-pills">
  <li class="active"><%= link_to "Stuff I'm giving away", dashboard_listed_path %></li>
  <li><%= link_to "My Requests", dashboard_requested_path %></li>
  <li><a href="#">Messages</a></li>
</ul>
<br>

<div class="container-inner">

<% current_user.gifts.each do | gift| %>
      <div>
        <a href="/gifts/<%= gift.id %>">
          <strong><%= gift.title %></strong>
          <em><%= gift.description %></em><br>
          <%= link_to time_ago_in_words(gift.created_at) + " ago" , gift %>   
          <hr>
        </a>
      </div>
  <% end %>
</div>  

app/views/dashboard/requested.html.erb
<h1>Dashboard#requested</h1>
<p>Find me in app/views/dashboard/index.html.erb</p>

<ul class="nav nav-pills">
  <li><%= link_to "Stuff I'm giving away", dashboard_listed_path %></li>
  <li class="active"><%= link_to "Stuff I've asked for", dashboard_requested_path %></li>
  <li><a href="#">Messages</a></li>
</ul>

<br>
<div class="container-inner">

  <!-- tabs -->
  <ul class="nav nav-tabs" role="tablist">
    <li class="active"><a href="#my-gifts" role="tab" data-toggle="tab">My Gifts</a></li>
    <li><a href="#my-requests" role="tab" data-toggle="tab">My Requests</a></li>
    <!-- broken link tag, should use link_to. Also could use helper method here to create whole li tags -->
    <li>a href="#profile" role="tab" data-toggle="tab">Profile</a></li>
  </ul>

  <!-- Tab panes -->
  <div class="tab-content">
    <div class="tab-pane active" id="my-gifts">
      <br>
      <% current_user.gifts.each do | gift| %>
        <div>
          <a href="/gifts/<%= gift.id %>/edit">
            <%= gift.title %>
          </a>
        </div>
      <% end %>

    </div>

    <div class="tab-pane" id="my-requests">
      
      <h2>My Requests</h2>
            <% current_user.requests.each do | request | %>
              <div>
                <a href="/gifts/<%= request.gift.id %>">
                  <%= request.gift.title %>
                </a>
              </div>
            <% end %>      

    </div>
</div>

app/views/gifts/_form.html.erb
<%= form_for(@gift) do |f| %>
  <% if @gift.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@gift.errors.count, "error") %> prohibited this gift from being saved:</h2>

      <ul>
      <% @gift.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field, form-group">
    <%= f.label :title, class: "sr-only" %><br>
    <%= f.text_field :title, placeholder: "Title", class: "form-control"  %>
  </div>

  <div class="field, form-group">
    <%= f.label :description, class: "sr-only" %><br>
    <%= f.text_area :description, placeholder: "Description", class: "form-control"  %>
  </div>
  <div class="field">
    <%= f.label :gifts_type, class: "sr-only" %><br>
    <%= f.text_field :gifts_type, placeholder: "Is it eadible, wearable, useable or companionable", class: "form-control"  %>
  </div>
  <div class="field">
    <%= f.label :comments, class: "sr-only" %><br>
    <%= f.text_area :comments, placeholder: "Comments", class: "form-control"  %>
  </div>
  <br>
  <button type="button" class="btn btn-warning">
      Upload an image
  </button>


  <%= f.submit "Submit", class: 'btn btn-info' %><br> 
<br>
<% end %>

app/views/gifts/edit.html.erb
<h1>Edit gift</h1>
<div class="row">
  <div class="col-xs-6 ">

    <%= render 'form' %>
    <%= link_to 'Show', @gift %> |
    <%= link_to 'Back', gifts_path %>

  </div>
</div>

app/views/gifts/index.html.erb
<h1>Browse gifts</h1>
<br>

<div class="container-inner">
  <% @gifts.each do | gift| %>
    <div class="gift">
      <a href="/gifts/<%= gift.id %>">
        <strong><%= gift.title %></strong>
      </a>
      <span>&nbsp</span><em><%= gift.description %></em><br>
      
      <div><%= link_to gift.user.profile_name, profile_path(gift.user) %> |  <%= time_ago_in_words(gift.created_at) + " ago" %>
      <a class="btn btn-inf pull-right" href="#" role="button">Enquire »</a>
      </div>   

      <% if gift.user == current_user %>
        <span class="admin">
          <%= link_to "Edit", edit_gift_path(gift) %> | 
        </span>
      <% end %>
      <hr>   
    </div>    
  <% end %>
  <hr>

  <div class="searchPane">
    <p>Filter: <input data-bind="value: filter, valueUpdate: 'afterkeydown'" /></p>
  </div>

  <div class="categoryPane">
    <div data-bind="visible: CategoryChoice">
      Choose a category of gift:
    <!--   <div><input type="checkbox" name="Category" value="Edible" data-bind="checked: giftEdible" /> Edible</div>
      <div><input type="checkbox" name="Category" value="Wearable" data-bind="checked: giftWearable" /> Wearable</div>
      <div><input type="checkbox" name="Category" value="Useable" data-bind="checked: giftUseable" /> Useable</div> -->
    </div>

  </div>


    <div class="browsePane" >
      <div data-bind="foreach: filteredgifts">
        <div  class="accordion" >
          <div class="giftHead" data-bind=" text: title"> 
          </div>
          <div class="pane">
            <p data-bind="text: title"></p>
            <p data-bind="text: description"></p>
          </div>

      </div>
      </div>
    </div>


  </div>






</div>


  
          <!-- <div class="btn pull-right">
            <div class: 'btn btn-info'>
          </div>   -->

app/views/gifts/jaz.html.erb
<div id="gift-list">
	<h2>Test</h2>
</div>

<div id="gift-details">
	

</div>


<!-- Handlebar template for gift-list -->
<script id="gift-list-item-template" type="text/x-handlebars-template">
  <div>
	  <a href="#" data-gift-id="{{id}}">
	  	{{title}}
	  </a>
  </div>
</script>


<!-- Handlebar template for gift-details-->
<script id="gift-details-template" type="text/x-handlebars-template">
	<div>
	  <h2>
	  	{{title}}
	  </h2>

	  <img src="{{image}}">
  </div>
</script>

app/views/gifts/new.html.erb
<h1>New gift</h1>
<div class="row">
  <div class="col-xs-6 ">
    <%= render 'form' %>
    <%= link_to 'Back', gifts_path %>
  </div>
<!--   <div class="col-xs-5">
    <div class="well">
    </div> -->
  </div>
</div>

app/views/gifts/show.html.erb
<p id="notice"><%= notice %></p>
<h1><%= @gift.title %></h1> 
<div class="container-inner">

<br>  
  
<p>
  <strong>Description:</strong>
  <%= @gift.description %>
</p>

<p>
  <strong>Type:</strong>
  <%= @gift.gifts_type %>
</p>

<p>
  <strong>Comments:</strong>
  <%= @gift.comments %>
</p>

<p>
  <strong>Listed By: <%= link_to @gift.user.profile_name, profile_path(@gift.user) %> </strong>
   
  
</p>

<em><%= time_ago_in_words(@gift.created_at) + " ago" %></em>

<br>
<br>
<hr>


<% if current_user.has_requested?(@gift) %>
  <div>Your request</div>
  <div> <%= current_user.request_for(@gift).message %></div>  
<% elsif @gift.user != current_user %>
  <%= form_for @request, url: request_gift_path(@gift) do |f| %>
    <div class="form-group">
      <%= f.label :message %>
      <%= f.text_area :message, class: "form-control" %>
     </div>
     <%= f.submit "Request Gift", class: 'btn btn-info' %> 
  <% end %>     
<% end %>


<img src="<%= @gift.image %>" />

<% if @gift.user == current_user %>
  <%= link_to 'Edit', edit_gift_path(@gift) %> |
  <%= link_to "Delete", @gift , method: :delete, data: { confirm: "are you sure you want to delete this gift?"} %>
<% end %>

<%= link_to 'Back', gifts_path %> 
</div>

app/views/landing/index.html.erb
<div class="welcome-message">
  <h2> You make a living from what you get, <br>
    but you make a life from what you give! </h2>
    <h1> GIFTe</h1>
</div>

<div id="form-signup">
  <div class="row">
    <div class="col-xs-4 col-xs-offset-4 ">
      <%= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
        <%= devise_error_messages! %>

        <div class="form-group">
          <%= f.label :first_name, class: "sr-only"%> <!-- screen reader only -->
          <%= f.text_field :first_name, placeholder: "first name", class: "form-control" %>
        </div>

        <div class="form-group">
          <%= f.label :last_name, class: "sr-only"  %>
          <%= f.text_field :last_name, placeholder: "last name", class: "form-control" %>
        </div>

        <div class="form-group">
          <%= f.label :profile_name, class: "sr-only"  %>
          <%= f.text_field :profile_name, placeholder: "profile name", class: "form-control" %>
        </div>

        <div class="form-group">
          <%= f.label :email, class: "sr-only"%>
          <%= f.email_field :email, autofocus: true, placeholder: "email", class: "form-control" %>
        </div>

        <div class="form-group">
          <%= f.label :location, class: "sr-only" %>
          <%= f.text_field :location, placeholder: "city", class: "form-control" %>
        </div>

        <div class="form-group">
          <%= f.label :password, class: "sr-only" %> 
            <% if @validatable %><i>(<%= @minimum_password_length %> characters minimum)</i><% end %>
          <%= f.password_field :password, autocomplete: "off", placeholder: "password (minimum 8 characters)", class: "form-control" %>
        </div>

        <div class="form-group">
          <%= f.label :password_confirmation, class: "sr-only" %>
          <%= f.password_field :password_confirmation, autocomplete: "off", placeholder: "confirmed password", class: "form-control" %>
        </div>
          
        <%= f.submit "Sign up", class: 'btn btn-info' %> 
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar-wrapper navbar-default navbar-fixed-top" role="navigation">
    <div class="container">
      <a class="navbar-brand" href="/gifts"><span class="glyphicon glyphicon-heart-empty"></span> GIFTe</a>
      <ul class="nav navbar-nav navbar-right">
        <li>
          <% if current_user %>
            <p class="navbar-text navbar-right">Welcome <%= link_to current_user.first_name, dashboard_path %></p>
            <li>
              <%= link_to "GIVE", new_gift_path %>
            </li>
            <li>
              <%= link_to "BROWSE", gifts_path %>
            </li>

            <!-- <p class="navbar-text navbar-right">Welcome <a href="#" class="navbar-link"><%= current_user.first_name %></a></p> -->
            <li>
              <%= link_to "Logout", destroy_user_session_path, method: :delete %>  
            </li>
          <% else %> 
            <li><%= link_to "Login", new_user_session_path %></li>
            <li><%= link_to "Sign up", new_user_registration_path %></li>
          <% end %>
        </li>
      </ul>
    </div>
  </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GIFTeconomy</title>
  
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>

  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">

  <!-- Optional theme -->
  <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css"> -->

  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
  
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= yield :head %>

</head>
<body>
  <%= render "layouts/navbar" %>
  <div class="container">
    <div class="jumbotron">
      <div class="inner-container">

        <% if notice %>
          <div class="alert alert-info alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
            <%= notice %>
          </div>
          
          <!-- devise configurations  -->
        <% end %>
        <% if alert %>
          <div class="alert alert-danger alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
            <%= alert %>
          </div>
        <% end %>

        <!-- <p class="notice"><%= notice %></p> --> <!-- devise configurations  -->
        <!-- <p class="alert"><%= alert %></p>  --><!-- devise configurations  -->
      
        <%= yield %> <!-- renders target page. -->
        
      </div>
    </div>
  </div>
</body>
</html>

app/views/layouts/landing.html.erb
<!DOCTYPE html>
<html lang="en-US" class="no-js">
  <head>

  <!-- ==============================================
    Title and Meta Tags
    =============================================== -->
    <meta charset="utf-8">
    <title>GIFTEconomy</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">

    <!-- Optional theme -->
    <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css"> -->
    <%= javascript_include_tag 'application' %>
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
    
    <%= stylesheet_link_tag    'application', media: 'all' %>
    
    <%= csrf_meta_tags %>

  </head>

<body>
  <nav class="navbar-wrapper navbar-default navbar-fixed-top" role="navigation">
    <div class="container">
      <ul class="nav navbar-nav navbar-right">
        <li>
          <% if current_user %>
            <p class="navbar-text navbar-right">Welcome <%= link_to current_user.first_name, edit_user_registration_path %></p>
            <!-- <p class="navbar-text navbar-right">Welcome <a href="#" class="navbar-link"><%= current_user.first_name %></a></p> -->
            <li>
              <%= link_to "logout", destroy_user_session_path, method: :delete %>  
            </li>
          <% else %> 
            <li><%= link_to "About", "#about" %></li> 
            <li><%= link_to "login", new_user_session_path %></li>
          <% end %>
        </li>
      </ul>
    </div>
  </nav>

  <div class="container">
    <% if notice %>
      <div class="alert alert-info alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <%= notice %>
      </div>
      
      <!-- devise configurations  -->
    <% end %>
    <% if alert %>
      <div class="alert alert-danger alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <%= alert %>
      </div>
    <% end %>
    <%= yield %>   
  </div>

  <div id="about">
    <h2>About Us</h2>
  </div>
</body>
</html>

app/views/profiles/show.html.erb
<h1><%= @user.profile_name%></h1>
<% if @gifts %>
  <% @gifts.each do |gift| %>
    <div class="well">
      <%= link_to gift.title, gift_path %><br>
      <em><%= gift.description %></em>
      <hr />
      <%= link_to time_ago_in_words(gift.created_at), gift_path(gift) %> ago
    </div>
  <% end %>
<% end %>